version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: growme-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.2
    container_name: growme-redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: growme-app
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis

volumes:
  mysql_data: